[cveDict]
  Type = "sqlite3"
  SQLite3Path = "/data/vulsctl/docker/cve.sqlite3"

[ovalDict]
  Type = "sqlite3"
  SQLite3Path = "/data/vulsctl/docker/oval.sqlite3"

[gost]
  Type = "sqlite3"
  SQLite3Path = "/data/vulsctl/docker/gost.sqlite3"

[exploit]
  Type = "sqlite3"
  SQLite3Path = "/data/vulsctl/docker/go-exploitdb.sqlite3"

[metasploit]
  Type = "sqlite3"
  SQLite3Path = "/data/vulsctl/docker/go-msfdb.sqlite3"

[kevuln]
  Type = "sqlite3"
  SQLite3Path = "/data/vulsctl/docker/go-kev.sqlite3"

[cti]
  Type = "sqlite3"
  SQLite3Path = "/data/vulsctl/docker/go-cti.sqlite3"

[default]

[servers]

[servers.nvd_exact]
type = "pseudo"
cpeNames = [ "cpe:/a:rubyonrails:rails:3.0.1" ]

[servers.nvd_rough]
type = "pseudo"
cpeNames = [ "cpe:/a:openssl:openssl:1.1.1" ]

[servers.nvd_vendor_product]
 type = "pseudo"
 cpeNames = [ "cpe:/a:djangoproject:django" ]

[servers.nvd_match_no_jvn]
type = "pseudo"
cpeNames = [ "cpe:/a:apache:tomcat:7.0.27" ]

[servers.jvn_vendor_product]
type = "pseudo"
cpeNames = [ "cpe:/a:hitachi_abb_power_grids:afs660:1.0.0" ]

[servers.jvn_vendor_product_nover]
type = "pseudo"
cpeNames = [ "cpe:/o:nec:aterm_wg2600hp2_firmware"]

[servers.bundler]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Gemfile.lock"]

[servers.dart]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/pubspec.lock"]

[servers.elixir]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/mix.lock"]

[servers.python-packaging]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/wheel.dist-info/METADATA"]

[servers.pip]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/requirements.txt"]

[servers.pipenv]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Pipfile.lock"]

[servers.poetry]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/poetry.lock"]

[servers.composer]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/composer.lock"]

[servers.npm]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/package-lock.json"]

[servers.yarn]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/yarn.lock"]

[servers.pnpm]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/pnpm-lock.yaml"]

[servers.cargo]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Cargo.lock"]

[servers.gomod]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/go.mod"]

[servers.gosum]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/go.sum"]

[servers.gobinary]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/gobinary"]

[servers.jar]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/log4j-core-2.13.0.jar"]

[servers.jar-by-sha1]
type = "pseudo"
# copy of log4j-core-2.13.0.jar, test for the case that go-dep-parser/jar returns multple entries for single JAR
lockfiles = ["./integration/data/lockfile/jar-by-sha1.jar"]

[servers.jar-in-jar]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/jar-in-jar.jar"]

[servers.war]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/juddiv3-war-3.3.5.war"]

[servers.pom]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/pom.xml"]

[servers.gradle]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/gradle.lockfile"]

[servers.nuget-lock]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/packages.lock.json"]

[servers.nuget-config]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/packages.config"]

[servers.dotnet-deps]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/datacollector.deps.json"]

[servers.dotnet-package-props]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Directory.Packages.props"]

[servers.conan]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/conan.lock"]

[servers.swift-cocoapods]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Podfile.lock"]

[servers.swift-swift]
type = "pseudo"
lockfiles = ["./integration/data/lockfile/Package.resolved"]
